version: "3.7"

services:
  database:
    image: postgres:11
    restart: always
    ports:
      - 6432:6432
    environment:
      POSTGRES_PASSWORD: ifrag
      POSTGRES_USER: ifrag
      POSTGRES_DB: ifrag

  backend:
    build:
      context: .
      args:
        MODE: dev
    env_file:
      - .env
    ports:
      - 5007:80
    volumes:
      - ./:/src/project
    depends_on:
      - database
